site_name: polymo
repo_url: https://github.com/dan1elt0m/polymo
repo_name: dan1elt0m/polymo
site_author: Daniel Tom
edit_uri: ""

theme:
  name: "material"
  font:
    text: Raleway
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  icon:
    logo: material/api
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

nav:
  - Home: index.md
  - Builder UI: builder-ui.md
  - Configuration: config.md
  - CLI: cli.md
  - API Reference:
    - polymo: api.md

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
