"""contacts — generated by the polymo builder.

Standalone Lakeflow Declarative Pipelines source. polymo is NOT needed
at runtime; edit this file freely.
"""

import time

import requests
import xml.etree.ElementTree as ET

BASE_URL = "https://api.maileon.com/1.0"
PATH = "/contacts"
PARAMS: dict = {}
HEADERS: dict = {"Authorization": "Basic REPLACE_ME_BASE64", "Accept": "application/vnd.maileon.api+xml"}
TIMEOUT = 30.0

# Behind a corporate TLS-intercepting proxy? `pip install truststore`
# and uncomment the next two lines:
# import truststore
# truststore.inject_into_ssl()

MAX_RETRIES = 5


def _should_retry(status):
    return 500 <= status <= 599 or status == 429


def _request(session, url, params):
    """GET with retries: statuses (500 <= status <= 599 or status == 429), backoff x2.0."""
    delay = 1.0
    for attempt in range(MAX_RETRIES + 1):
        try:
            response = session.get(url, params=params, timeout=TIMEOUT)
        except requests.exceptions.Timeout:
            if not True or attempt == MAX_RETRIES:
                raise
        except requests.exceptions.ConnectionError:
            if not True or attempt == MAX_RETRIES:
                raise
        else:
            if not _should_retry(response.status_code) or attempt == MAX_RETRIES:
                response.raise_for_status()
                return response
        time.sleep(delay)
        delay = min(delay * 2.0, 30.0) if 30.0 > 0 else delay * 2.0
    raise RuntimeError("unreachable")


XML_RECORD_PATH = ".//contact"


def _records(root):
    """Flatten each matched XML element into a record dict."""
    records = []
    for element in root.findall(XML_RECORD_PATH):
        record = {f"@{key}": value for key, value in element.attrib.items()}
        for child in element:
            record[child.tag] = child.text
        records.append(record)
    return records


def fetch_records(extra_params=None, path=None):
    """Yield records, paginating with page_index."""
    url_path = path or PATH
    session = requests.Session()
    session.headers.update(HEADERS)
    page = 0
    while True:
        params = dict(PARAMS)
        if extra_params:
            params.update(extra_params)
        params["page_size"] = 100
        params["page_index"] = page
        response = _request(session, f"{BASE_URL}{url_path}", params)
        payload = ET.fromstring(response.content)
        records = _records(payload)
        if not records:
            return
        yield from records
        total = response.headers.get("X-Pages")
        if total is not None and page >= int(total):
            return
        page += 1


from pyspark import pipelines as dp  # noqa: E402
from pyspark.sql import SparkSession  # noqa: E402

spark = SparkSession.getActiveSession()


@dp.table(name="contacts")
def contacts():
    rows = list(fetch_records())
    return spark.createDataFrame(rows)
