"""posts — generated by the polymo builder.

Standalone Lakeflow Declarative Pipelines source. polymo is NOT needed
at runtime; edit this file freely.
"""

import time

import requests
import json
import os

BASE_URL = "https://api.example.com"
PATH = "/posts"
PARAMS: dict = {}
HEADERS: dict = {}
TIMEOUT = 30.0

# One entry per partition; each is fetched independently (parallelized
# across executors in the dp table below).
# records are not tagged with their source endpoint
WINDOWS = [{"path": "/a"}, {"path": "/b"}]

# Where the incremental cursor is stored between runs. Point this at a
# durable path (e.g. a Databricks Volume: /Volumes/cat/schema/vol/posts.json).
STATE_PATH = "posts_state.json"
LAST_CURSOR = {"value": None}


def _read_state():
    if not os.path.exists(STATE_PATH):
        return {}
    with open(STATE_PATH) as fh:
        return json.load(fh)


def _write_state(cursor):
    if cursor is None:
        return
    with open(STATE_PATH, "w") as fh:
        json.dump({"cursor": cursor}, fh)

# Fill in your client secret. For anything beyond local testing, fetch it
# from a secret store instead of keeping it in this file, e.g.:
#   CLIENT_SECRET = dbutils.secrets.get("my-scope", "my-key")
CLIENT_SECRET = "REPLACE_ME"
TOKEN_URL = "https://api.example.com/token"


def get_token():
    """Fetch an OAuth2 access token (client credentials grant)."""
    payload = {
        "grant_type": "client_credentials",
        "client_id": "cid",
        "client_secret": CLIENT_SECRET,
    }
    response = requests.post(TOKEN_URL, data=payload, timeout=TIMEOUT)
    response.raise_for_status()
    return response.json()["access_token"]

# Behind a corporate TLS-intercepting proxy? `pip install truststore`
# and uncomment the next two lines:
# import truststore
# truststore.inject_into_ssl()

MAX_RETRIES = 5


def _should_retry(status):
    return 500 <= status <= 599 or status == 429


def _request(session, url, params):
    """GET with retries: statuses (500 <= status <= 599 or status == 429), backoff x2.0."""
    delay = 1.0
    for attempt in range(MAX_RETRIES + 1):
        try:
            response = session.get(url, params=params, timeout=TIMEOUT)
        except requests.exceptions.Timeout:
            if not True or attempt == MAX_RETRIES:
                raise
        except requests.exceptions.ConnectionError:
            if not True or attempt == MAX_RETRIES:
                raise
        else:
            if not _should_retry(response.status_code) or attempt == MAX_RETRIES:
                response.raise_for_status()
                return response
        time.sleep(delay)
        delay = min(delay * 2.0, 30.0) if 30.0 > 0 else delay * 2.0
    raise RuntimeError("unreachable")


def _records(payload):
    """Normalise a response payload to a list of dicts."""
    if isinstance(payload, list):
        records = payload
    elif isinstance(payload, dict):
        records = [payload]
        for key in ("data", "items", "results"):
            if key in payload and isinstance(payload[key], list):
                records = payload[key]
                break
    else:
        records = [payload]
    records = [r if isinstance(r, dict) else {"record": r} for r in records]
    return records


def fetch_records(extra_params=None, path=None):
    """Yield records from the API (single page)."""
    url_path = path or PATH
    session = requests.Session()
    session.headers.update(HEADERS)
    session.headers["Authorization"] = f"Bearer {get_token()}"
    params = dict(PARAMS)
    if extra_params:
        params.update(extra_params)
    state_cursor = _read_state().get("cursor")
    if state_cursor is not None:
        params["since"] = state_cursor
    response = _request(session, f"{BASE_URL}{url_path}", params)
    records = _records(response.json())
    yield from records
    for record in records:
        value = record.get("updated")
        if value is not None and (LAST_CURSOR["value"] is None or value > LAST_CURSOR["value"]):
            LAST_CURSOR["value"] = value


from pyspark import pipelines as dp  # noqa: E402
from pyspark.sql import SparkSession  # noqa: E402

spark = SparkSession.getActiveSession()

SCHEMA = "id BIGINT, updated STRING"


@dp.table(name="posts")
def posts():
    sc = spark.sparkContext
    rows = sc.parallelize(WINDOWS, len(WINDOWS)).flatMap(
        lambda window: list(fetch_records(**window))
    ).collect()
    # fetch_records runs on executors under parallelize/flatMap, so LAST_CURSOR
    # mutations happen in worker processes and never reach the driver; compute
    # the cursor here instead, from the rows collected back on the driver.
    cursor_values = [
        r.get("updated")
        for r in rows
        if isinstance(r, dict) and r.get("updated") is not None
    ]
    _write_state(max(cursor_values) if cursor_values else None)
    return spark.createDataFrame(rows, schema=SCHEMA)
