"""posts — generated by the polymo builder.

Standalone Lakeflow Declarative Pipelines source. polymo is NOT needed
at runtime; edit this file freely.
"""

import time
from typing import Any, Iterator

import requests

BASE_URL: str = "https://api.example.com"
PATH: str = "/posts"
PARAMS: dict[str, Any] = {}
HEADERS: dict[str, str] = {}
TIMEOUT: float = 30.0

# Behind a corporate TLS-intercepting proxy? `pip install truststore`
# and uncomment the next two lines:
# import truststore
# truststore.inject_into_ssl()

MAX_RETRIES: int = 5


def _should_retry(status: int) -> bool:
    return 500 <= status <= 599 or status == 429


def _request(session: requests.Session, url: str, params: dict[str, Any] | None) -> requests.Response:
    """GET with retries: statuses (500 <= status <= 599 or status == 429), backoff x2.0."""
    delay = 1.0
    for attempt in range(MAX_RETRIES + 1):
        try:
            response = session.get(url, params=params, timeout=TIMEOUT)
        except requests.exceptions.Timeout:
            if not True or attempt == MAX_RETRIES:
                raise
        except requests.exceptions.ConnectionError:
            if not True or attempt == MAX_RETRIES:
                raise
        else:
            if not _should_retry(response.status_code) or attempt == MAX_RETRIES:
                response.raise_for_status()
                return response
        time.sleep(delay)
        delay = min(delay * 2.0, 30.0) if 30.0 > 0 else delay * 2.0
    raise RuntimeError("unreachable")


def _records(payload: Any) -> list[dict[str, Any]]:
    """Normalise a response payload to a list of dicts."""
    if isinstance(payload, list):
        records = payload
    elif isinstance(payload, dict):
        records = [payload]
        for key in ("data", "items", "results"):
            if key in payload and isinstance(payload[key], list):
                records = payload[key]
                break
    else:
        records = [payload]
    records = [r if isinstance(r, dict) else {"record": r} for r in records]
    return records


# Not used by the streaming reader below (which calls fetch_page directly);
# kept for ad-hoc/batch runs and the builder preview.
def fetch_records(extra_params: dict[str, Any] | None = None, path: str | None = None) -> Iterator[dict[str, Any]]:
    """Yield records, paginating with page."""
    url_path = path or PATH
    session = requests.Session()
    session.headers.update(HEADERS)
    page = 1
    while True:
        params = dict(PARAMS)
        if extra_params:
            params.update(extra_params)
        params["page"] = page
        response = _request(session, f"{BASE_URL}{url_path}", params)
        payload = response.json()
        records = _records(payload)
        if not records:
            return
        yield from records
        page += 1


def fetch_page(page_index: int) -> list[dict[str, Any]]:
    """Fetch one page by index; returns a list of records."""
    session = requests.Session()
    session.headers.update(HEADERS)
    params = dict(PARAMS)
    params["page"] = 1 + page_index
    response = _request(session, f"{BASE_URL}{PATH}", params)
    return _records(response.json())


from pyspark import pipelines as dp  # noqa: E402
from pyspark.sql import SparkSession  # noqa: E402

spark = SparkSession.getActiveSession()

SCHEMA: str = "id BIGINT"


from pyspark.sql.datasource import DataSource, SimpleDataSourceStreamReader  # noqa: E402

# Assumes SCHEMA is a comma-separated "name TYPE" DDL string (as emitted
# above); column names are taken as the first whitespace-separated token.
COLUMNS: list[str] = [f.split()[0] for f in SCHEMA.split(",")]


class _Reader(SimpleDataSourceStreamReader):
    def initialOffset(self) -> dict[str, Any]:
        return {"page": 0}

    def read(self, start: dict[str, Any]) -> tuple[Iterator[tuple], dict[str, Any]]:
        page = start["page"]
        records = fetch_page(page)
        rows = [tuple(r.get(c) for c in COLUMNS) for r in records]
        next_page = page + 1 if records else page
        return iter(rows), {"page": next_page}

    def readBetweenOffsets(self, start: dict[str, Any], end: dict[str, Any]) -> Iterator[tuple]:
        rows = []
        for page in range(start["page"], end["page"]):
            for r in fetch_page(page):
                rows.append(tuple(r.get(c) for c in COLUMNS))
        return iter(rows)


class RestStreamSource(DataSource):
    @classmethod
    def name(cls) -> str:
        return "posts_stream"

    def schema(self) -> str:
        return SCHEMA

    def simpleStreamReader(self, schema: Any) -> "_Reader":
        return _Reader()


spark.dataSource.register(RestStreamSource)


@dp.table(name="posts")
def posts():
    return spark.readStream.format("posts_stream").load()
